In [ ]:
# numpy属性

In [1]:
import numpy as np
array = np.array([[1,2,3],
                  [2,3,4]])

In [5]:
print(array) 
print(array.ndim)  # 维数
print(array.shape) # 形状
print(array.size)  #  元素个数

[[1 2 3]
 [2 3 4]]
2
(2, 3)
6


In [6]:
# numpy创建array

In [7]:
import numpy as np

In [10]:
a = np.array([2,23,4],dtype=np.int32)  # 矩阵，定义np的类型
a

array([ 2, 23,  4])

In [12]:
print(a.dtype)

int32


In [16]:
a = np.array([[2,23,4],
             [2,32,4]])
a.dtype

dtype('int32')

In [19]:
a = np.zeros((3,4))

In [27]:
a = np.ones((3,4),dtype = np.int32)
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [28]:
a = np.empty((3,4),dtype = np.int32)
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [29]:
a = np.arange(10,20,2)   # 生成数列，范围10到20，步长2
a

array([10, 12, 14, 16, 18])

In [36]:
a = np.arange(12).reshape((3,4))
print(a)
a

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
a = np.linspace(1,10,20) # 从1到10的20个数，
print(a)
b = np.linspace(1,10,5)
b

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [38]:
b = np.linspace(1,10,6).reshape((2,3))
b.dtype

dtype('float64')

In [39]:
# numpy基础运算

In [40]:
import numpy as np

In [43]:
a = np.array([10,20,30,40])
print(a,a.dtype)
b = np.arange(4)
print(b,b.dtype)

[10 20 30 40] int32
[0 1 2 3] int32


In [46]:
print(a-b)
a+b    # 矩阵加减

[10 21 32 43]


array([10, 21, 32, 43])

In [47]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [49]:
10*np.sin(a)   # sin,cos,tan也一样

array([-5.44021111,  9.12945251, -9.88031624,  7.4511316 ])

In [51]:
print(b<3)  # 判断b矩阵中小于3
print(b==3)

[ True  True  True False]
[False False False  True]


In [56]:
a = np.array([[1,1],
             [0,1]])
b = np.arange(4).reshape((2,2))
print(a)
print(b)

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]


In [58]:
a*b   # 矩阵中元素乘元素

array([[0, 1],
       [0, 3]])

In [60]:
print(np.dot(a,b))  # 矩阵乘法
print(a.dot(b))

[[2 4]
 [2 3]]
[[2 4]
 [2 3]]


In [68]:
a = np.random.random((2,4))
print(a)
print(np.sum(a))
print(np.min(a))
print(np.max(a))

[[0.50361776 0.25526421 0.92149679 0.11573064]
 [0.89518242 0.49818691 0.03346843 0.8985831 ]]
4.121530254483218
0.03346843093821106
0.9214967850172371


In [72]:
print(np.sum(a,axis = 1))  # axis = 1 表示求矩阵中每一行中的求和   1行0列
print(np.min(a,axis = 0))  # axis = 0 表示求矩阵中每一行列的最小值

[1.7961094  2.32542085]
[0.50361776 0.25526421 0.03346843 0.11573064]


In [94]:
A = np.arange(14,2,-1).reshape((3,4))
print(A)
print(np.argmin(A))   # 最小值索引值
print("最大值索引：",np.argmax(A))   # 最大值索引值
print("平均值：",A.mean())
print(np.average(A))
print(np.median(A))

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
11
最大值索引： 0
平均值： 8.5
8.5
8.5


In [96]:
print("累加:",np.cumsum(A))
print("累差：\n",np.diff(A))
print("非零数：",np.nonzero(A))
print("排序：",np.sort(A))   # 每一行进行排序

累加: [ 14  27  39  50  60  69  77  84  90  95  99 102]
累差：
 [[-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]]
非零数： (array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))
排序： [[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]


In [98]:
print(np.transpose(A)) # 矩阵的转置
print((A.T).dot(A))

[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[332 302 272 242]
 [302 275 248 221]
 [272 248 224 200]
 [242 221 200 179]]


In [101]:
print(np.clip(A,5,9))  # 小于5的都变成5，大于9的变成9，中间保持不变

[[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]


In [107]:
print(A)
print('axis0,表示列的平均值：',np.mean(A,axis=0))  # 0表示列    ，表示行的个数
print('axis1,表示行的平均值：',np.mean(A,axis=1))

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
axis0,表示列的平均值： [10.  9.  8.  7.]
axis1,表示行的平均值： [12.5  8.5  4.5]


In [108]:
# numpy索引

In [109]:
import numpy as np

In [113]:
A = np.arange(3,15)
print(A)
print(A[3])

[ 3  4  5  6  7  8  9 10 11 12 13 14]
6


In [123]:
A = np.arange(3,15).reshape((3,4))
print(A)
print(A[2])   # 第三行的值
print(A[1][1]) # 2,2值
print(A[2,3])
print(A[2,:]) # 第三行所有数
print(A[:,2]) # 第三列所有数
print(A[1,1:3])

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[11 12 13 14]
8
14
[11 12 13 14]
[ 5  9 13]
[8 9]


In [127]:
for row in A:   #迭代行
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [130]:
for column in A.T:   # 转置，迭代列
    print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [137]:
print(A.flat)   # 迭代器 返回一个object
print(A.flatten())   # 返回列表，矩阵变成一列
for item in A.flat:  # 迭代每一个元素
    print(item)

[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14


In [138]:
# numpy array合并

In [147]:
import numpy as np
A = np.array([1,1,1,1])
B = np.array([2,2,2,2])
C = np.vstack((A,B))   # 上下合并
D = np.hstack((A,B))   # 变成一行

print(C)   # 合并行变成矩阵
print(D)
print(A.shape,C.shape)  # 合并后两行四列
print(A.shape,D.shape)   # 合并后变成一行

print(A.T.shape)  # A.T不能把横向数列变成竖着的数列
print(A[np.newaxis,:].shape)  #  列不变，加行（加维度）
print(A[:,np.newaxis])     #   行不变，加列维度

[[1 1 1 1]
 [2 2 2 2]]
[1 1 1 1 2 2 2 2]
(4,) (2, 4)
(4,) (8,)
(4,)
(1, 4)
[[1]
 [1]
 [1]
 [1]]


In [153]:
A = np.array([1,1,1,1])[:,np.newaxis]   # 变成列向量
B = np.array([2,2,2,2])[:,np.newaxis]  

E = np.concatenate((A,B,B,A),axis=0)  # 上下合并
F = np.concatenate((A,B,B,A),axis=1) # 左右合并
print(E)
print(F)


[[1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]
 [1]]
[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]


In [154]:
# numpy 分割array

In [166]:
import numpy as np 
A = np.arange(12).reshape((3,4))
print(A)
print(np.split(A,2,axis=1))  # split 分割  纵向分割   列分割
print(np.split(A,3,axis=0))  # split 分割  纵向分割  行分割

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [168]:
print(np.array_split(A,3,axis=1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


In [172]:
print(A)
print(np.vsplit(A,3))  # 横向分割
print(np.hsplit(A,2)) # 纵向分割

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [174]:
# numpy复制
import numpy as np
a = np.arange(4)
a

array([0, 1, 2, 3])

In [177]:
b=a   # 
c=a
d=a

In [181]:
a[0] = 11
a

array([11,  1,  2,  3])

In [183]:
b is a   # b,a是同一个对象    a,b,c,d都是同一个对象


True

In [ ]:
b = a.copy()    # deep copy  ,两个对象